languageCode = "en-UK"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://meenaparam.com"
googleAnalytics = "UA-106317524-1"
theme = "hugo-vitae"

[params]
  author = "Meenakshi Parameshwaran"
  title = "Meenakshi Parameshwaran's CV"
  description = "Meenakshi Parameshwaran's CV"
  avatar = "meena_profile.png"
  email_full = "mailto:meena.param@gmail.com"
  github = "meenaparam"
  twitter = "meenaparam"
  google_maps = "https://www.google.co.uk/maps/place/UCL+Computer+Science/@51.523188,-0.1324129,15z/data=!4m5!3m4!1s0x0:0x921db3ae5ef57ce7!8m2!3d51.523188!4d-0.1324129"
  address = "UCL"
  postcode = "WC1E 7JE"
  city = "London"
  country = "United Kingdom"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
